#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    # libdynamixel
    obj = bld.new_task_gen('cxx', 'staticlib')
    obj.source = "instruction.cpp packet.cpp status.cpp usb2dynamixel.cpp"
    obj.target = 'dynamixel'
    obj.want_libtool = 1

    # install all includes (custom-made)
    import os, glob, types
    p = bld.srcnode.abspath() + '/src/dynamixel'
    r = glob.glob(p + '*/*.hpp') + glob.glob(p + '*.hpp')
    for i in r:
        k = os.path.split(i)
        d = os.path.split(k[0])
        bld.install_files('${PREFIX}/include/' + d[1], i)
    #libs
    p = bld.srcnode.abspath() + '/build/default/'
    r = glob.glob(p + '*/*/*.a')
    for i in r:
        bld.install_files('${PREFIX}/lib/', i)
