#!/usr/bin/env python
# encoding: utf-8


def build(bld):
    obj = bld.new_task_gen('cxx', 'program')
    obj.source = "test.cpp"
    obj.includes = '. ..'
    obj.target = 'dynamixel_test'

    obj = bld.new_task_gen('cxx', 'program')
    obj.source = "omnipointer_arm.cpp"
    obj.includes = '. ..'
    obj.target = 'omnipointer_arm'
