#!/usr/bin/env python
# encoding: utf-8


def build(bld):
    bld(features='cxx cxxprogram', source='dynamixel2.cpp', target="dynamixel2", includes=". ..", uselib="BOOST_PROGRAM_OPTIONS", uselib_local="dynamixel")